//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TexcelASP_SamNicEntities : DbContext
    {
        public TexcelASP_SamNicEntities()
            : base("name=TexcelASP_SamNicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategorieEmploi> CategorieEmploi { get; set; }
        public virtual DbSet<Classification> Classification { get; set; }
        public virtual DbSet<Developpeur> Developpeur { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Equipe> Equipe { get; set; }
        public virtual DbSet<EquipeEmploye> EquipeEmploye { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Jeu> Jeu { get; set; }
        public virtual DbSet<Platforme> Platforme { get; set; }
        public virtual DbSet<ProjetTest> ProjetTest { get; set; }
        public virtual DbSet<SystemeExploitation> SystemeExploitation { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<Theme> Theme { get; set; }
        public virtual DbSet<TypePlatforme> TypePlatforme { get; set; }
        public virtual DbSet<TypeTest> TypeTest { get; set; }
    }
}
