//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelASP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Jeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jeu()
        {
            this.Jeu1 = new HashSet<Jeu>();
            this.Jeu2 = new HashSet<Jeu>();
        }
    
        
        public int id { get; set; }
        [Display(Name = "Nom")]
        public string nom { get; set; }
        public string description { get; set; }
        public string configMinimal { get; set; }
        public int genre { get; set; }
        public int theme { get; set; }
        public int classification { get; set; }
        public int developpeur { get; set; }
        public int platforme { get; set; }
    
        public virtual Classification Classification1 { get; set; }
        public virtual Developpeur Developpeur1 { get; set; }
        public virtual Genre Genre1 { get; set; }
        public virtual Platforme Platforme1 { get; set; }
        public virtual Theme Theme1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jeu> Jeu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jeu> Jeu2 { get; set; }
    }
}
