//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platforme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Platforme()
        {
            this.Jeu = new HashSet<Jeu>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string configuration { get; set; }
        public int typePlatforme { get; set; }
        public string systemeExploitation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jeu> Jeu { get; set; }
        public virtual SystemeExploitation SystemeExploitation1 { get; set; }
        public virtual TypePlatforme TypePlatforme1 { get; set; }
    }
}
