//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewJeu
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string description { get; set; }
        public string configMinimal { get; set; }
        public string genre { get; set; }
        public string theme { get; set; }
        public string classification { get; set; }
        public string developpeur { get; set; }
        public string platforme { get; set; }
        public string tag { get; set; }
    }
}
