//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPlatforme
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string configuration { get; set; }
        public string typePlatforme { get; set; }
        public string systemeExploitation { get; set; }
        public string tag { get; set; }
    }
}
